receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

  natsjetstream:
    url: "nats://localhost:4222"
    stream: "telemetry"
    consumer_name: "grafts"
    subjects:
      traces: "otlp.proto.traces"
      metrics: "otlp.proto.metrics"
      logs: "otlp.proto.logs"

  # SNMP receiver (uncomment and configure to use)
  # snmp:
  #   collection_interval: 60s
  #   auth:
  #     public_v2c:
  #       version: v2c
  #       community: public
  #   targets:
  #     - host: 192.168.1.1
  #       auth: public_v2c
  #       metric_groups: [system]
  #   metric_groups:
  #     system:
  #       metrics:
  #         - oid: "1.3.6.1.2.1.1.3.0"
  #           metric_name: snmp.system.uptime
  #           type: gauge
  #           unit: cs

exporters:
  debug:
    verbosity: detailed

  natsjetstream:
    url: "nats://localhost:4222"
    stream: "telemetry"
    subjects:
      traces: "otlp.proto.traces"
      metrics: "otlp.proto.metrics"
      logs: "otlp.proto.logs"
    publish_async: true

service:
  pipelines:
    traces/ingest-to-nats:
      receivers: [otlp]
      exporters: [natsjetstream]
    traces/ingest-from-nats:
      receivers: [natsjetstream]
      exporters: [debug]
