receivers:
  natsjetstream:
    url: "nats://localhost:4222"
    domain: "production"
    stream: "telemetry"
    consumer_name: "grafts"
    subjects:
      traces: "otlp.proto.traces"
      metrics: "otlp.proto.metrics"
      logs: "otlp.proto.logs"

exporters:
  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [natsjetstream]
      exporters: [debug]
    metrics:
      receivers: [natsjetstream]
      exporters: [debug]
    logs:
      receivers: [natsjetstream]
      exporters: [debug]
