// Code generated by weaver. DO NOT EDIT.
// Source: https://olly.garden/schemas/grafts/pgbouncerreceiver/0.1.0

// Package telemetry builds the metrics pgbouncerreceiver reports about the
// system it monitors.
//
// The registry behind the schema URL above is the only place these are
// defined. Editing this file by hand puts the code and the parity report out of
// step, which is the drift the registry exists to remove.
package telemetry

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
)

// Attribute values this registry declares. An attribute whose upstream
// convention defines fewer values than the monitored system reports is an open
// enum: the component may record a value not listed here, and says so in the
// metric's note.

const (
	// AttributeDBClientConnectionStateIdle is `idle` for db.client.connection.state.
	AttributeDBClientConnectionStateIdle = "idle"
	// AttributeDBClientConnectionStateUsed is `used` for db.client.connection.state.
	AttributeDBClientConnectionStateUsed = "used"
)

const (
	// AttributeNetworkIODirectionTransmit is `transmit` for network.io.direction.
	AttributeNetworkIODirectionTransmit = "transmit"
	// AttributeNetworkIODirectionReceive is `receive` for network.io.direction.
	AttributeNetworkIODirectionReceive = "receive"
)

const (
	// AttributePgbouncerClientConnectionStateActive is `active` for pgbouncer.client.connection.state.
	AttributePgbouncerClientConnectionStateActive = "active"
	// AttributePgbouncerClientConnectionStateWaiting is `waiting` for pgbouncer.client.connection.state.
	AttributePgbouncerClientConnectionStateWaiting = "waiting"
	// AttributePgbouncerClientConnectionStateActiveCancel is `active_cancel` for pgbouncer.client.connection.state.
	AttributePgbouncerClientConnectionStateActiveCancel = "active_cancel"
	// AttributePgbouncerClientConnectionStateWaitingCancel is `waiting_cancel` for pgbouncer.client.connection.state.
	AttributePgbouncerClientConnectionStateWaitingCancel = "waiting_cancel"
)

const (
	// AttributePgbouncerClientStateFree is `free` for pgbouncer.client.state.
	AttributePgbouncerClientStateFree = "free"
	// AttributePgbouncerClientStateUsed is `used` for pgbouncer.client.state.
	AttributePgbouncerClientStateUsed = "used"
	// AttributePgbouncerClientStateLogin is `login` for pgbouncer.client.state.
	AttributePgbouncerClientStateLogin = "login"
	// AttributePgbouncerClientStateActive is `active` for pgbouncer.client.state.
	AttributePgbouncerClientStateActive = "active"
	// AttributePgbouncerClientStateWaiting is `waiting` for pgbouncer.client.state.
	AttributePgbouncerClientStateWaiting = "waiting"
	// AttributePgbouncerClientStateIdle is `idle` for pgbouncer.client.state.
	AttributePgbouncerClientStateIdle = "idle"
)

const (
	// AttributePgbouncerDNSCacheTypeName is `name` for pgbouncer.dns.cache.type.
	AttributePgbouncerDNSCacheTypeName = "name"
	// AttributePgbouncerDNSCacheTypeZone is `zone` for pgbouncer.dns.cache.type.
	AttributePgbouncerDNSCacheTypeZone = "zone"
)

const (
	// AttributePgbouncerPeerClient is `client` for pgbouncer.peer.
	AttributePgbouncerPeerClient = "client"
	// AttributePgbouncerPeerServer is `server` for pgbouncer.peer.
	AttributePgbouncerPeerServer = "server"
)

const (
	// AttributePgbouncerPreparedStatementOperationParse is `parse` for pgbouncer.prepared_statement.operation.
	AttributePgbouncerPreparedStatementOperationParse = "parse"
	// AttributePgbouncerPreparedStatementOperationBind is `bind` for pgbouncer.prepared_statement.operation.
	AttributePgbouncerPreparedStatementOperationBind = "bind"
)

const (
	// AttributePgbouncerServerStateFree is `free` for pgbouncer.server.state.
	AttributePgbouncerServerStateFree = "free"
	// AttributePgbouncerServerStateUsed is `used` for pgbouncer.server.state.
	AttributePgbouncerServerStateUsed = "used"
)

// MetricConfig gates a single metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`
}

// MetricsConfig gates every metric this component can report. A metric that is
// disabled records nothing and is absent from the output entirely, rather than
// being emitted empty.
type MetricsConfig struct {
	DBClientConnectionCount              MetricConfig `mapstructure:"db.client.connection.count"`
	DBClientConnectionIdleMin            MetricConfig `mapstructure:"db.client.connection.idle.min"`
	DBClientConnectionMax                MetricConfig `mapstructure:"db.client.connection.max"`
	DBClientConnectionPendingRequests    MetricConfig `mapstructure:"db.client.connection.pending_requests"`
	PgbouncerClientConnectionCount       MetricConfig `mapstructure:"pgbouncer.client.connection.count"`
	PgbouncerClientConnectionDetailCount MetricConfig `mapstructure:"pgbouncer.client.connection.detail.count"`
	PgbouncerClientConnectionMax         MetricConfig `mapstructure:"pgbouncer.client.connection.max"`
	PgbouncerClientCount                 MetricConfig `mapstructure:"pgbouncer.client.count"`
	PgbouncerClientWaitMax               MetricConfig `mapstructure:"pgbouncer.client.wait.max"`
	PgbouncerClientWaitTime              MetricConfig `mapstructure:"pgbouncer.client.wait.time"`
	PgbouncerDatabaseConnectionCount     MetricConfig `mapstructure:"pgbouncer.database.connection.count"`
	PgbouncerDatabaseConnectionMax       MetricConfig `mapstructure:"pgbouncer.database.connection.max"`
	PgbouncerDatabaseCount               MetricConfig `mapstructure:"pgbouncer.database.count"`
	PgbouncerDatabaseDisabled            MetricConfig `mapstructure:"pgbouncer.database.disabled"`
	PgbouncerDatabasePaused              MetricConfig `mapstructure:"pgbouncer.database.paused"`
	PgbouncerDatabaseReservePoolSize     MetricConfig `mapstructure:"pgbouncer.database.reserve_pool.size"`
	PgbouncerDNSCacheCount               MetricConfig `mapstructure:"pgbouncer.dns.cache.count"`
	PgbouncerDNSQueryCount               MetricConfig `mapstructure:"pgbouncer.dns.query.count"`
	PgbouncerNetworkIO                   MetricConfig `mapstructure:"pgbouncer.network.io"`
	PgbouncerPoolCount                   MetricConfig `mapstructure:"pgbouncer.pool.count"`
	PgbouncerPreparedStatementCount      MetricConfig `mapstructure:"pgbouncer.prepared_statement.count"`
	PgbouncerQueryCount                  MetricConfig `mapstructure:"pgbouncer.query.count"`
	PgbouncerQueryTime                   MetricConfig `mapstructure:"pgbouncer.query.time"`
	PgbouncerServerAssignmentCount       MetricConfig `mapstructure:"pgbouncer.server.assignment.count"`
	PgbouncerServerCount                 MetricConfig `mapstructure:"pgbouncer.server.count"`
	PgbouncerTransactionCount            MetricConfig `mapstructure:"pgbouncer.transaction.count"`
	PgbouncerTransactionTime             MetricConfig `mapstructure:"pgbouncer.transaction.time"`
	PgbouncerUserConnectionMax           MetricConfig `mapstructure:"pgbouncer.user.connection.max"`
	PgbouncerUserCount                   MetricConfig `mapstructure:"pgbouncer.user.count"`
}

// DefaultMetricsConfig enables every metric the registry marks `recommended` or
// `required`, and leaves `opt_in` metrics off.
func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		DBClientConnectionCount:              MetricConfig{Enabled: true},
		DBClientConnectionIdleMin:            MetricConfig{Enabled: true},
		DBClientConnectionMax:                MetricConfig{Enabled: true},
		DBClientConnectionPendingRequests:    MetricConfig{Enabled: true},
		PgbouncerClientConnectionCount:       MetricConfig{Enabled: true},
		PgbouncerClientConnectionDetailCount: MetricConfig{Enabled: true},
		PgbouncerClientConnectionMax:         MetricConfig{Enabled: true},
		PgbouncerClientCount:                 MetricConfig{Enabled: true},
		PgbouncerClientWaitMax:               MetricConfig{Enabled: true},
		PgbouncerClientWaitTime:              MetricConfig{Enabled: true},
		PgbouncerDatabaseConnectionCount:     MetricConfig{Enabled: true},
		PgbouncerDatabaseConnectionMax:       MetricConfig{Enabled: true},
		PgbouncerDatabaseCount:               MetricConfig{Enabled: true},
		PgbouncerDatabaseDisabled:            MetricConfig{Enabled: true},
		PgbouncerDatabasePaused:              MetricConfig{Enabled: true},
		PgbouncerDatabaseReservePoolSize:     MetricConfig{Enabled: true},
		PgbouncerDNSCacheCount:               MetricConfig{Enabled: true},
		PgbouncerDNSQueryCount:               MetricConfig{Enabled: true},
		PgbouncerNetworkIO:                   MetricConfig{Enabled: true},
		PgbouncerPoolCount:                   MetricConfig{Enabled: true},
		PgbouncerPreparedStatementCount:      MetricConfig{Enabled: true},
		PgbouncerQueryCount:                  MetricConfig{Enabled: true},
		PgbouncerQueryTime:                   MetricConfig{Enabled: true},
		PgbouncerServerAssignmentCount:       MetricConfig{Enabled: true},
		PgbouncerServerCount:                 MetricConfig{Enabled: true},
		PgbouncerTransactionCount:            MetricConfig{Enabled: true},
		PgbouncerTransactionTime:             MetricConfig{Enabled: true},
		PgbouncerUserConnectionMax:           MetricConfig{Enabled: true},
		PgbouncerUserCount:                   MetricConfig{Enabled: true},
	}
}

type metricDBClientConnectionCount struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricDBClientConnectionCount) init() {
	m.data.SetName("db.client.connection.count")
	m.data.SetDescription("Connections PgBouncer holds to PostgreSQL, by state.")
	m.data.SetUnit("{connection}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

// DBClientConnectionCountAttributes carries the attributes of db.client.connection.count.
type DBClientConnectionCountAttributes struct {
	// DBClientConnectionPoolName is `db.client.connection.pool.name`.
	DBClientConnectionPoolName string
	// DBClientConnectionState is `db.client.connection.state`.
	DBClientConnectionState string
	// DBNamespace is `db.namespace`.
	DBNamespace string
	// PgbouncerDatabaseAlias is `pgbouncer.database.alias`.
	PgbouncerDatabaseAlias string
	// PgbouncerUser is `pgbouncer.user`.
	PgbouncerUser string
	// ServerAddress is `server.address`.
	ServerAddress string
	// ServerPort is `server.port`.
	ServerPort int64
}

func (m *metricDBClientConnectionCount) record(start, ts pcommon.Timestamp, value int64, attrs DBClientConnectionCountAttributes) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
	dp.Attributes().PutStr("db.client.connection.pool.name", attrs.DBClientConnectionPoolName)
	dp.Attributes().PutStr("db.client.connection.state", attrs.DBClientConnectionState)
	dp.Attributes().PutStr("db.namespace", attrs.DBNamespace)
	dp.Attributes().PutStr("pgbouncer.database.alias", attrs.PgbouncerDatabaseAlias)
	dp.Attributes().PutStr("pgbouncer.user", attrs.PgbouncerUser)
	dp.Attributes().PutStr("server.address", attrs.ServerAddress)
	dp.Attributes().PutInt("server.port", attrs.ServerPort)
}

func (m *metricDBClientConnectionCount) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricDBClientConnectionIdleMin struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricDBClientConnectionIdleMin) init() {
	m.data.SetName("db.client.connection.idle.min")
	m.data.SetDescription("Server connections PgBouncer keeps open when idle.")
	m.data.SetUnit("{connection}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

// DBClientConnectionIdleMinAttributes carries the attributes of db.client.connection.idle.min.
type DBClientConnectionIdleMinAttributes struct {
	// DBClientConnectionPoolName is `db.client.connection.pool.name`.
	DBClientConnectionPoolName string
	// DBNamespace is `db.namespace`.
	DBNamespace string
	// PgbouncerDatabaseAlias is `pgbouncer.database.alias`.
	PgbouncerDatabaseAlias string
	// ServerAddress is `server.address`.
	ServerAddress string
	// ServerPort is `server.port`.
	ServerPort int64
}

func (m *metricDBClientConnectionIdleMin) record(start, ts pcommon.Timestamp, value int64, attrs DBClientConnectionIdleMinAttributes) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
	dp.Attributes().PutStr("db.client.connection.pool.name", attrs.DBClientConnectionPoolName)
	dp.Attributes().PutStr("db.namespace", attrs.DBNamespace)
	dp.Attributes().PutStr("pgbouncer.database.alias", attrs.PgbouncerDatabaseAlias)
	dp.Attributes().PutStr("server.address", attrs.ServerAddress)
	dp.Attributes().PutInt("server.port", attrs.ServerPort)
}

func (m *metricDBClientConnectionIdleMin) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricDBClientConnectionMax struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricDBClientConnectionMax) init() {
	m.data.SetName("db.client.connection.max")
	m.data.SetDescription("Maximum server connections PgBouncer will open for a pool.")
	m.data.SetUnit("{connection}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

// DBClientConnectionMaxAttributes carries the attributes of db.client.connection.max.
type DBClientConnectionMaxAttributes struct {
	// DBClientConnectionPoolName is `db.client.connection.pool.name`.
	DBClientConnectionPoolName string
	// DBNamespace is `db.namespace`.
	DBNamespace string
	// PgbouncerDatabaseAlias is `pgbouncer.database.alias`.
	PgbouncerDatabaseAlias string
	// ServerAddress is `server.address`.
	ServerAddress string
	// ServerPort is `server.port`.
	ServerPort int64
}

func (m *metricDBClientConnectionMax) record(start, ts pcommon.Timestamp, value int64, attrs DBClientConnectionMaxAttributes) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
	dp.Attributes().PutStr("db.client.connection.pool.name", attrs.DBClientConnectionPoolName)
	dp.Attributes().PutStr("db.namespace", attrs.DBNamespace)
	dp.Attributes().PutStr("pgbouncer.database.alias", attrs.PgbouncerDatabaseAlias)
	dp.Attributes().PutStr("server.address", attrs.ServerAddress)
	dp.Attributes().PutInt("server.port", attrs.ServerPort)
}

func (m *metricDBClientConnectionMax) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricDBClientConnectionPendingRequests struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricDBClientConnectionPendingRequests) init() {
	m.data.SetName("db.client.connection.pending_requests")
	m.data.SetDescription("Clients queued waiting for a server connection.")
	m.data.SetUnit("{request}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

// DBClientConnectionPendingRequestsAttributes carries the attributes of db.client.connection.pending_requests.
type DBClientConnectionPendingRequestsAttributes struct {
	// DBClientConnectionPoolName is `db.client.connection.pool.name`.
	DBClientConnectionPoolName string
	// DBNamespace is `db.namespace`.
	DBNamespace string
	// PgbouncerDatabaseAlias is `pgbouncer.database.alias`.
	PgbouncerDatabaseAlias string
	// PgbouncerUser is `pgbouncer.user`.
	PgbouncerUser string
	// ServerAddress is `server.address`.
	ServerAddress string
	// ServerPort is `server.port`.
	ServerPort int64
}

func (m *metricDBClientConnectionPendingRequests) record(start, ts pcommon.Timestamp, value int64, attrs DBClientConnectionPendingRequestsAttributes) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
	dp.Attributes().PutStr("db.client.connection.pool.name", attrs.DBClientConnectionPoolName)
	dp.Attributes().PutStr("db.namespace", attrs.DBNamespace)
	dp.Attributes().PutStr("pgbouncer.database.alias", attrs.PgbouncerDatabaseAlias)
	dp.Attributes().PutStr("pgbouncer.user", attrs.PgbouncerUser)
	dp.Attributes().PutStr("server.address", attrs.ServerAddress)
	dp.Attributes().PutInt("server.port", attrs.ServerPort)
}

func (m *metricDBClientConnectionPendingRequests) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerClientConnectionCount struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerClientConnectionCount) init() {
	m.data.SetName("pgbouncer.client.connection.count")
	m.data.SetDescription("Client connections held by PgBouncer, by state.")
	m.data.SetUnit("{connection}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

// PgbouncerClientConnectionCountAttributes carries the attributes of pgbouncer.client.connection.count.
type PgbouncerClientConnectionCountAttributes struct {
	// DBNamespace is `db.namespace`.
	DBNamespace string
	// PgbouncerClientConnectionState is `pgbouncer.client.connection.state`.
	PgbouncerClientConnectionState string
	// PgbouncerDatabaseAlias is `pgbouncer.database.alias`.
	PgbouncerDatabaseAlias string
	// PgbouncerUser is `pgbouncer.user`.
	PgbouncerUser string
	// ServerAddress is `server.address`.
	ServerAddress string
	// ServerPort is `server.port`.
	ServerPort int64
}

func (m *metricPgbouncerClientConnectionCount) record(start, ts pcommon.Timestamp, value int64, attrs PgbouncerClientConnectionCountAttributes) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
	dp.Attributes().PutStr("db.namespace", attrs.DBNamespace)
	dp.Attributes().PutStr("pgbouncer.client.connection.state", attrs.PgbouncerClientConnectionState)
	dp.Attributes().PutStr("pgbouncer.database.alias", attrs.PgbouncerDatabaseAlias)
	dp.Attributes().PutStr("pgbouncer.user", attrs.PgbouncerUser)
	dp.Attributes().PutStr("server.address", attrs.ServerAddress)
	dp.Attributes().PutInt("server.port", attrs.ServerPort)
}

func (m *metricPgbouncerClientConnectionCount) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerClientConnectionDetailCount struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerClientConnectionDetailCount) init() {
	m.data.SetName("pgbouncer.client.connection.detail.count")
	m.data.SetDescription("Client connections aggregated by database, role and connection state.")
	m.data.SetUnit("{connection}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

// PgbouncerClientConnectionDetailCountAttributes carries the attributes of pgbouncer.client.connection.detail.count.
type PgbouncerClientConnectionDetailCountAttributes struct {
	// DBNamespace is `db.namespace`.
	DBNamespace string
	// PgbouncerClientState is `pgbouncer.client.state`.
	PgbouncerClientState string
	// PgbouncerDatabaseAlias is `pgbouncer.database.alias`.
	PgbouncerDatabaseAlias string
	// PgbouncerUser is `pgbouncer.user`.
	PgbouncerUser string
}

func (m *metricPgbouncerClientConnectionDetailCount) record(start, ts pcommon.Timestamp, value int64, attrs PgbouncerClientConnectionDetailCountAttributes) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
	dp.Attributes().PutStr("db.namespace", attrs.DBNamespace)
	dp.Attributes().PutStr("pgbouncer.client.state", attrs.PgbouncerClientState)
	dp.Attributes().PutStr("pgbouncer.database.alias", attrs.PgbouncerDatabaseAlias)
	dp.Attributes().PutStr("pgbouncer.user", attrs.PgbouncerUser)
}

func (m *metricPgbouncerClientConnectionDetailCount) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerClientConnectionMax struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerClientConnectionMax) init() {
	m.data.SetName("pgbouncer.client.connection.max")
	m.data.SetDescription("Maximum client connections PgBouncer accepts process-wide.")
	m.data.SetUnit("{connection}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPgbouncerClientConnectionMax) record(start, ts pcommon.Timestamp, value int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
}

func (m *metricPgbouncerClientConnectionMax) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerClientCount struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerClientCount) init() {
	m.data.SetName("pgbouncer.client.count")
	m.data.SetDescription("Client slots, by state.")
	m.data.SetUnit("{client}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

// PgbouncerClientCountAttributes carries the attributes of pgbouncer.client.count.
type PgbouncerClientCountAttributes struct {
	// PgbouncerClientState is `pgbouncer.client.state`.
	PgbouncerClientState string
}

func (m *metricPgbouncerClientCount) record(start, ts pcommon.Timestamp, value int64, attrs PgbouncerClientCountAttributes) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
	dp.Attributes().PutStr("pgbouncer.client.state", attrs.PgbouncerClientState)
}

func (m *metricPgbouncerClientCount) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerClientWaitMax struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerClientWaitMax) init() {
	m.data.SetName("pgbouncer.client.wait.max")
	m.data.SetDescription("Age of the oldest client connection still waiting for a server connection.")
	m.data.SetUnit("s")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

// PgbouncerClientWaitMaxAttributes carries the attributes of pgbouncer.client.wait.max.
type PgbouncerClientWaitMaxAttributes struct {
	// DBNamespace is `db.namespace`.
	DBNamespace string
	// PgbouncerDatabaseAlias is `pgbouncer.database.alias`.
	PgbouncerDatabaseAlias string
	// PgbouncerUser is `pgbouncer.user`.
	PgbouncerUser string
}

func (m *metricPgbouncerClientWaitMax) record(start, ts pcommon.Timestamp, value float64, attrs PgbouncerClientWaitMaxAttributes) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(value)
	dp.Attributes().PutStr("db.namespace", attrs.DBNamespace)
	dp.Attributes().PutStr("pgbouncer.database.alias", attrs.PgbouncerDatabaseAlias)
	dp.Attributes().PutStr("pgbouncer.user", attrs.PgbouncerUser)
}

func (m *metricPgbouncerClientWaitMax) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Gauge().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Gauge().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerClientWaitTime struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerClientWaitTime) init() {
	m.data.SetName("pgbouncer.client.wait.time")
	m.data.SetDescription("Time clients have spent waiting for a server connection.")
	m.data.SetUnit("s")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

// PgbouncerClientWaitTimeAttributes carries the attributes of pgbouncer.client.wait.time.
type PgbouncerClientWaitTimeAttributes struct {
	// DBNamespace is `db.namespace`.
	DBNamespace string
	// PgbouncerDatabaseAlias is `pgbouncer.database.alias`.
	PgbouncerDatabaseAlias string
}

func (m *metricPgbouncerClientWaitTime) record(start, ts pcommon.Timestamp, value float64, attrs PgbouncerClientWaitTimeAttributes) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(value)
	dp.Attributes().PutStr("db.namespace", attrs.DBNamespace)
	dp.Attributes().PutStr("pgbouncer.database.alias", attrs.PgbouncerDatabaseAlias)
}

func (m *metricPgbouncerClientWaitTime) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerDatabaseConnectionCount struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerDatabaseConnectionCount) init() {
	m.data.SetName("pgbouncer.database.connection.count")
	m.data.SetDescription("Server connections currently open for a configured database.")
	m.data.SetUnit("{connection}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

// PgbouncerDatabaseConnectionCountAttributes carries the attributes of pgbouncer.database.connection.count.
type PgbouncerDatabaseConnectionCountAttributes struct {
	// DBNamespace is `db.namespace`.
	DBNamespace string
	// PgbouncerDatabaseAlias is `pgbouncer.database.alias`.
	PgbouncerDatabaseAlias string
	// ServerAddress is `server.address`.
	ServerAddress string
	// ServerPort is `server.port`.
	ServerPort int64
}

func (m *metricPgbouncerDatabaseConnectionCount) record(start, ts pcommon.Timestamp, value int64, attrs PgbouncerDatabaseConnectionCountAttributes) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
	dp.Attributes().PutStr("db.namespace", attrs.DBNamespace)
	dp.Attributes().PutStr("pgbouncer.database.alias", attrs.PgbouncerDatabaseAlias)
	dp.Attributes().PutStr("server.address", attrs.ServerAddress)
	dp.Attributes().PutInt("server.port", attrs.ServerPort)
}

func (m *metricPgbouncerDatabaseConnectionCount) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerDatabaseConnectionMax struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerDatabaseConnectionMax) init() {
	m.data.SetName("pgbouncer.database.connection.max")
	m.data.SetDescription("Maximum server connections allowed for a configured database.")
	m.data.SetUnit("{connection}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

// PgbouncerDatabaseConnectionMaxAttributes carries the attributes of pgbouncer.database.connection.max.
type PgbouncerDatabaseConnectionMaxAttributes struct {
	// DBNamespace is `db.namespace`.
	DBNamespace string
	// PgbouncerDatabaseAlias is `pgbouncer.database.alias`.
	PgbouncerDatabaseAlias string
	// ServerAddress is `server.address`.
	ServerAddress string
	// ServerPort is `server.port`.
	ServerPort int64
}

func (m *metricPgbouncerDatabaseConnectionMax) record(start, ts pcommon.Timestamp, value int64, attrs PgbouncerDatabaseConnectionMaxAttributes) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
	dp.Attributes().PutStr("db.namespace", attrs.DBNamespace)
	dp.Attributes().PutStr("pgbouncer.database.alias", attrs.PgbouncerDatabaseAlias)
	dp.Attributes().PutStr("server.address", attrs.ServerAddress)
	dp.Attributes().PutInt("server.port", attrs.ServerPort)
}

func (m *metricPgbouncerDatabaseConnectionMax) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerDatabaseCount struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerDatabaseCount) init() {
	m.data.SetName("pgbouncer.database.count")
	m.data.SetDescription("Databases configured in PgBouncer.")
	m.data.SetUnit("{database}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPgbouncerDatabaseCount) record(start, ts pcommon.Timestamp, value int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
}

func (m *metricPgbouncerDatabaseCount) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerDatabaseDisabled struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerDatabaseDisabled) init() {
	m.data.SetName("pgbouncer.database.disabled")
	m.data.SetDescription("1 while a configured database is disabled, else 0.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

// PgbouncerDatabaseDisabledAttributes carries the attributes of pgbouncer.database.disabled.
type PgbouncerDatabaseDisabledAttributes struct {
	// DBNamespace is `db.namespace`.
	DBNamespace string
	// PgbouncerDatabaseAlias is `pgbouncer.database.alias`.
	PgbouncerDatabaseAlias string
	// ServerAddress is `server.address`.
	ServerAddress string
	// ServerPort is `server.port`.
	ServerPort int64
}

func (m *metricPgbouncerDatabaseDisabled) record(start, ts pcommon.Timestamp, value int64, attrs PgbouncerDatabaseDisabledAttributes) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
	dp.Attributes().PutStr("db.namespace", attrs.DBNamespace)
	dp.Attributes().PutStr("pgbouncer.database.alias", attrs.PgbouncerDatabaseAlias)
	dp.Attributes().PutStr("server.address", attrs.ServerAddress)
	dp.Attributes().PutInt("server.port", attrs.ServerPort)
}

func (m *metricPgbouncerDatabaseDisabled) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Gauge().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Gauge().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerDatabasePaused struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerDatabasePaused) init() {
	m.data.SetName("pgbouncer.database.paused")
	m.data.SetDescription("1 while a configured database is paused, else 0.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

// PgbouncerDatabasePausedAttributes carries the attributes of pgbouncer.database.paused.
type PgbouncerDatabasePausedAttributes struct {
	// DBNamespace is `db.namespace`.
	DBNamespace string
	// PgbouncerDatabaseAlias is `pgbouncer.database.alias`.
	PgbouncerDatabaseAlias string
	// ServerAddress is `server.address`.
	ServerAddress string
	// ServerPort is `server.port`.
	ServerPort int64
}

func (m *metricPgbouncerDatabasePaused) record(start, ts pcommon.Timestamp, value int64, attrs PgbouncerDatabasePausedAttributes) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
	dp.Attributes().PutStr("db.namespace", attrs.DBNamespace)
	dp.Attributes().PutStr("pgbouncer.database.alias", attrs.PgbouncerDatabaseAlias)
	dp.Attributes().PutStr("server.address", attrs.ServerAddress)
	dp.Attributes().PutInt("server.port", attrs.ServerPort)
}

func (m *metricPgbouncerDatabasePaused) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Gauge().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Gauge().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerDatabaseReservePoolSize struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerDatabaseReservePoolSize) init() {
	m.data.SetName("pgbouncer.database.reserve_pool.size")
	m.data.SetDescription("Additional server connections allowed once a pool is saturated.")
	m.data.SetUnit("{connection}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

// PgbouncerDatabaseReservePoolSizeAttributes carries the attributes of pgbouncer.database.reserve_pool.size.
type PgbouncerDatabaseReservePoolSizeAttributes struct {
	// DBNamespace is `db.namespace`.
	DBNamespace string
	// PgbouncerDatabaseAlias is `pgbouncer.database.alias`.
	PgbouncerDatabaseAlias string
	// ServerAddress is `server.address`.
	ServerAddress string
	// ServerPort is `server.port`.
	ServerPort int64
}

func (m *metricPgbouncerDatabaseReservePoolSize) record(start, ts pcommon.Timestamp, value int64, attrs PgbouncerDatabaseReservePoolSizeAttributes) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
	dp.Attributes().PutStr("db.namespace", attrs.DBNamespace)
	dp.Attributes().PutStr("pgbouncer.database.alias", attrs.PgbouncerDatabaseAlias)
	dp.Attributes().PutStr("server.address", attrs.ServerAddress)
	dp.Attributes().PutInt("server.port", attrs.ServerPort)
}

func (m *metricPgbouncerDatabaseReservePoolSize) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerDNSCacheCount struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerDNSCacheCount) init() {
	m.data.SetName("pgbouncer.dns.cache.count")
	m.data.SetDescription("Entries in PgBouncer\u0027s DNS cache.")
	m.data.SetUnit("{entry}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

// PgbouncerDNSCacheCountAttributes carries the attributes of pgbouncer.dns.cache.count.
type PgbouncerDNSCacheCountAttributes struct {
	// PgbouncerDNSCacheType is `pgbouncer.dns.cache.type`.
	PgbouncerDNSCacheType string
}

func (m *metricPgbouncerDNSCacheCount) record(start, ts pcommon.Timestamp, value int64, attrs PgbouncerDNSCacheCountAttributes) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
	dp.Attributes().PutStr("pgbouncer.dns.cache.type", attrs.PgbouncerDNSCacheType)
}

func (m *metricPgbouncerDNSCacheCount) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerDNSQueryCount struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerDNSQueryCount) init() {
	m.data.SetName("pgbouncer.dns.query.count")
	m.data.SetDescription("DNS queries PgBouncer has in flight.")
	m.data.SetUnit("{query}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPgbouncerDNSQueryCount) record(start, ts pcommon.Timestamp, value int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
}

func (m *metricPgbouncerDNSQueryCount) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerNetworkIO struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerNetworkIO) init() {
	m.data.SetName("pgbouncer.network.io")
	m.data.SetDescription("Network traffic PgBouncer has proxied.")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

// PgbouncerNetworkIOAttributes carries the attributes of pgbouncer.network.io.
type PgbouncerNetworkIOAttributes struct {
	// DBNamespace is `db.namespace`.
	DBNamespace string
	// NetworkIODirection is `network.io.direction`.
	NetworkIODirection string
	// PgbouncerDatabaseAlias is `pgbouncer.database.alias`.
	PgbouncerDatabaseAlias string
}

func (m *metricPgbouncerNetworkIO) record(start, ts pcommon.Timestamp, value int64, attrs PgbouncerNetworkIOAttributes) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
	dp.Attributes().PutStr("db.namespace", attrs.DBNamespace)
	dp.Attributes().PutStr("network.io.direction", attrs.NetworkIODirection)
	dp.Attributes().PutStr("pgbouncer.database.alias", attrs.PgbouncerDatabaseAlias)
}

func (m *metricPgbouncerNetworkIO) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerPoolCount struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerPoolCount) init() {
	m.data.SetName("pgbouncer.pool.count")
	m.data.SetDescription("Active connection pools.")
	m.data.SetUnit("{pool}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPgbouncerPoolCount) record(start, ts pcommon.Timestamp, value int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
}

func (m *metricPgbouncerPoolCount) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerPreparedStatementCount struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerPreparedStatementCount) init() {
	m.data.SetName("pgbouncer.prepared_statement.count")
	m.data.SetDescription("Extended-query-protocol messages PgBouncer handled for prepared statements.")
	m.data.SetUnit("{message}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

// PgbouncerPreparedStatementCountAttributes carries the attributes of pgbouncer.prepared_statement.count.
type PgbouncerPreparedStatementCountAttributes struct {
	// DBNamespace is `db.namespace`.
	DBNamespace string
	// PgbouncerDatabaseAlias is `pgbouncer.database.alias`.
	PgbouncerDatabaseAlias string
	// PgbouncerPeer is `pgbouncer.peer`.
	PgbouncerPeer string
	// PgbouncerPreparedStatementOperation is `pgbouncer.prepared_statement.operation`.
	PgbouncerPreparedStatementOperation string
}

func (m *metricPgbouncerPreparedStatementCount) record(start, ts pcommon.Timestamp, value int64, attrs PgbouncerPreparedStatementCountAttributes) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
	dp.Attributes().PutStr("db.namespace", attrs.DBNamespace)
	dp.Attributes().PutStr("pgbouncer.database.alias", attrs.PgbouncerDatabaseAlias)
	dp.Attributes().PutStr("pgbouncer.peer", attrs.PgbouncerPeer)
	dp.Attributes().PutStr("pgbouncer.prepared_statement.operation", attrs.PgbouncerPreparedStatementOperation)
}

func (m *metricPgbouncerPreparedStatementCount) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerQueryCount struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerQueryCount) init() {
	m.data.SetName("pgbouncer.query.count")
	m.data.SetDescription("SQL queries pooled by PgBouncer.")
	m.data.SetUnit("{query}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

// PgbouncerQueryCountAttributes carries the attributes of pgbouncer.query.count.
type PgbouncerQueryCountAttributes struct {
	// DBNamespace is `db.namespace`.
	DBNamespace string
	// PgbouncerDatabaseAlias is `pgbouncer.database.alias`.
	PgbouncerDatabaseAlias string
}

func (m *metricPgbouncerQueryCount) record(start, ts pcommon.Timestamp, value int64, attrs PgbouncerQueryCountAttributes) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
	dp.Attributes().PutStr("db.namespace", attrs.DBNamespace)
	dp.Attributes().PutStr("pgbouncer.database.alias", attrs.PgbouncerDatabaseAlias)
}

func (m *metricPgbouncerQueryCount) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerQueryTime struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerQueryTime) init() {
	m.data.SetName("pgbouncer.query.time")
	m.data.SetDescription("Time PgBouncer spent executing queries against PostgreSQL.")
	m.data.SetUnit("s")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

// PgbouncerQueryTimeAttributes carries the attributes of pgbouncer.query.time.
type PgbouncerQueryTimeAttributes struct {
	// DBNamespace is `db.namespace`.
	DBNamespace string
	// PgbouncerDatabaseAlias is `pgbouncer.database.alias`.
	PgbouncerDatabaseAlias string
}

func (m *metricPgbouncerQueryTime) record(start, ts pcommon.Timestamp, value float64, attrs PgbouncerQueryTimeAttributes) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(value)
	dp.Attributes().PutStr("db.namespace", attrs.DBNamespace)
	dp.Attributes().PutStr("pgbouncer.database.alias", attrs.PgbouncerDatabaseAlias)
}

func (m *metricPgbouncerQueryTime) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerServerAssignmentCount struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerServerAssignmentCount) init() {
	m.data.SetName("pgbouncer.server.assignment.count")
	m.data.SetDescription("Client connections assigned a server connection since process start.")
	m.data.SetUnit("{assignment}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

// PgbouncerServerAssignmentCountAttributes carries the attributes of pgbouncer.server.assignment.count.
type PgbouncerServerAssignmentCountAttributes struct {
	// DBNamespace is `db.namespace`.
	DBNamespace string
	// PgbouncerDatabaseAlias is `pgbouncer.database.alias`.
	PgbouncerDatabaseAlias string
}

func (m *metricPgbouncerServerAssignmentCount) record(start, ts pcommon.Timestamp, value int64, attrs PgbouncerServerAssignmentCountAttributes) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
	dp.Attributes().PutStr("db.namespace", attrs.DBNamespace)
	dp.Attributes().PutStr("pgbouncer.database.alias", attrs.PgbouncerDatabaseAlias)
}

func (m *metricPgbouncerServerAssignmentCount) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerServerCount struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerServerCount) init() {
	m.data.SetName("pgbouncer.server.count")
	m.data.SetDescription("Server slots, by state.")
	m.data.SetUnit("{server}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

// PgbouncerServerCountAttributes carries the attributes of pgbouncer.server.count.
type PgbouncerServerCountAttributes struct {
	// PgbouncerServerState is `pgbouncer.server.state`.
	PgbouncerServerState string
}

func (m *metricPgbouncerServerCount) record(start, ts pcommon.Timestamp, value int64, attrs PgbouncerServerCountAttributes) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
	dp.Attributes().PutStr("pgbouncer.server.state", attrs.PgbouncerServerState)
}

func (m *metricPgbouncerServerCount) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerTransactionCount struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerTransactionCount) init() {
	m.data.SetName("pgbouncer.transaction.count")
	m.data.SetDescription("SQL transactions pooled by PgBouncer.")
	m.data.SetUnit("{transaction}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

// PgbouncerTransactionCountAttributes carries the attributes of pgbouncer.transaction.count.
type PgbouncerTransactionCountAttributes struct {
	// DBNamespace is `db.namespace`.
	DBNamespace string
	// PgbouncerDatabaseAlias is `pgbouncer.database.alias`.
	PgbouncerDatabaseAlias string
}

func (m *metricPgbouncerTransactionCount) record(start, ts pcommon.Timestamp, value int64, attrs PgbouncerTransactionCountAttributes) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
	dp.Attributes().PutStr("db.namespace", attrs.DBNamespace)
	dp.Attributes().PutStr("pgbouncer.database.alias", attrs.PgbouncerDatabaseAlias)
}

func (m *metricPgbouncerTransactionCount) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerTransactionTime struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerTransactionTime) init() {
	m.data.SetName("pgbouncer.transaction.time")
	m.data.SetDescription("Time PgBouncer server connections spent inside a transaction.")
	m.data.SetUnit("s")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

// PgbouncerTransactionTimeAttributes carries the attributes of pgbouncer.transaction.time.
type PgbouncerTransactionTimeAttributes struct {
	// DBNamespace is `db.namespace`.
	DBNamespace string
	// PgbouncerDatabaseAlias is `pgbouncer.database.alias`.
	PgbouncerDatabaseAlias string
}

func (m *metricPgbouncerTransactionTime) record(start, ts pcommon.Timestamp, value float64, attrs PgbouncerTransactionTimeAttributes) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(value)
	dp.Attributes().PutStr("db.namespace", attrs.DBNamespace)
	dp.Attributes().PutStr("pgbouncer.database.alias", attrs.PgbouncerDatabaseAlias)
}

func (m *metricPgbouncerTransactionTime) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerUserConnectionMax struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerUserConnectionMax) init() {
	m.data.SetName("pgbouncer.user.connection.max")
	m.data.SetDescription("Maximum server connections PgBouncer opens per login role.")
	m.data.SetUnit("{connection}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPgbouncerUserConnectionMax) record(start, ts pcommon.Timestamp, value int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
}

func (m *metricPgbouncerUserConnectionMax) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

type metricPgbouncerUserCount struct {
	data     pmetric.Metric
	capacity int
	config   MetricConfig
}

func (m *metricPgbouncerUserCount) init() {
	m.data.SetName("pgbouncer.user.count")
	m.data.SetDescription("Login roles known to PgBouncer.")
	m.data.SetUnit("{user}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPgbouncerUserCount) record(start, ts pcommon.Timestamp, value int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(value)
}

func (m *metricPgbouncerUserCount) emit(ms pmetric.MetricSlice) {
	if !m.config.Enabled || m.data.Sum().DataPoints().Len() == 0 {
		return
	}
	// One scrape is a good predictor of the next -- the datapoint count follows
	// the target's pool and database count, which rarely moves -- so carry it
	// over and let the next init presize instead of regrowing from empty.
	m.capacity = m.data.Sum().DataPoints().Len()
	m.data.MoveTo(ms.AppendEmpty())
	m.init()
}

// MetricsBuilder accumulates one scrape's worth of datapoints and hands them
// over as a pmetric.Metrics.
//
// It is not safe for concurrent use: a scraper owns one and drives it from a
// single scrape.
type MetricsBuilder struct {
	startTime                                  pcommon.Timestamp
	scopeName                                  string
	scopeVersion                               string
	metricDBClientConnectionCount              metricDBClientConnectionCount
	metricDBClientConnectionIdleMin            metricDBClientConnectionIdleMin
	metricDBClientConnectionMax                metricDBClientConnectionMax
	metricDBClientConnectionPendingRequests    metricDBClientConnectionPendingRequests
	metricPgbouncerClientConnectionCount       metricPgbouncerClientConnectionCount
	metricPgbouncerClientConnectionDetailCount metricPgbouncerClientConnectionDetailCount
	metricPgbouncerClientConnectionMax         metricPgbouncerClientConnectionMax
	metricPgbouncerClientCount                 metricPgbouncerClientCount
	metricPgbouncerClientWaitMax               metricPgbouncerClientWaitMax
	metricPgbouncerClientWaitTime              metricPgbouncerClientWaitTime
	metricPgbouncerDatabaseConnectionCount     metricPgbouncerDatabaseConnectionCount
	metricPgbouncerDatabaseConnectionMax       metricPgbouncerDatabaseConnectionMax
	metricPgbouncerDatabaseCount               metricPgbouncerDatabaseCount
	metricPgbouncerDatabaseDisabled            metricPgbouncerDatabaseDisabled
	metricPgbouncerDatabasePaused              metricPgbouncerDatabasePaused
	metricPgbouncerDatabaseReservePoolSize     metricPgbouncerDatabaseReservePoolSize
	metricPgbouncerDNSCacheCount               metricPgbouncerDNSCacheCount
	metricPgbouncerDNSQueryCount               metricPgbouncerDNSQueryCount
	metricPgbouncerNetworkIO                   metricPgbouncerNetworkIO
	metricPgbouncerPoolCount                   metricPgbouncerPoolCount
	metricPgbouncerPreparedStatementCount      metricPgbouncerPreparedStatementCount
	metricPgbouncerQueryCount                  metricPgbouncerQueryCount
	metricPgbouncerQueryTime                   metricPgbouncerQueryTime
	metricPgbouncerServerAssignmentCount       metricPgbouncerServerAssignmentCount
	metricPgbouncerServerCount                 metricPgbouncerServerCount
	metricPgbouncerTransactionCount            metricPgbouncerTransactionCount
	metricPgbouncerTransactionTime             metricPgbouncerTransactionTime
	metricPgbouncerUserConnectionMax           metricPgbouncerUserConnectionMax
	metricPgbouncerUserCount                   metricPgbouncerUserCount
}

// NewMetricsBuilder returns a builder gated by config. startTime is the process
// start, reported on every cumulative datapoint so a consumer can tell a reset
// from a genuine drop.
func NewMetricsBuilder(config MetricsConfig, startTime pcommon.Timestamp, scopeName, scopeVersion string) *MetricsBuilder {
	mb := &MetricsBuilder{
		startTime:                                  startTime,
		scopeName:                                  scopeName,
		scopeVersion:                               scopeVersion,
		metricDBClientConnectionCount:              metricDBClientConnectionCount{data: pmetric.NewMetric(), config: config.DBClientConnectionCount},
		metricDBClientConnectionIdleMin:            metricDBClientConnectionIdleMin{data: pmetric.NewMetric(), config: config.DBClientConnectionIdleMin},
		metricDBClientConnectionMax:                metricDBClientConnectionMax{data: pmetric.NewMetric(), config: config.DBClientConnectionMax},
		metricDBClientConnectionPendingRequests:    metricDBClientConnectionPendingRequests{data: pmetric.NewMetric(), config: config.DBClientConnectionPendingRequests},
		metricPgbouncerClientConnectionCount:       metricPgbouncerClientConnectionCount{data: pmetric.NewMetric(), config: config.PgbouncerClientConnectionCount},
		metricPgbouncerClientConnectionDetailCount: metricPgbouncerClientConnectionDetailCount{data: pmetric.NewMetric(), config: config.PgbouncerClientConnectionDetailCount},
		metricPgbouncerClientConnectionMax:         metricPgbouncerClientConnectionMax{data: pmetric.NewMetric(), config: config.PgbouncerClientConnectionMax},
		metricPgbouncerClientCount:                 metricPgbouncerClientCount{data: pmetric.NewMetric(), config: config.PgbouncerClientCount},
		metricPgbouncerClientWaitMax:               metricPgbouncerClientWaitMax{data: pmetric.NewMetric(), config: config.PgbouncerClientWaitMax},
		metricPgbouncerClientWaitTime:              metricPgbouncerClientWaitTime{data: pmetric.NewMetric(), config: config.PgbouncerClientWaitTime},
		metricPgbouncerDatabaseConnectionCount:     metricPgbouncerDatabaseConnectionCount{data: pmetric.NewMetric(), config: config.PgbouncerDatabaseConnectionCount},
		metricPgbouncerDatabaseConnectionMax:       metricPgbouncerDatabaseConnectionMax{data: pmetric.NewMetric(), config: config.PgbouncerDatabaseConnectionMax},
		metricPgbouncerDatabaseCount:               metricPgbouncerDatabaseCount{data: pmetric.NewMetric(), config: config.PgbouncerDatabaseCount},
		metricPgbouncerDatabaseDisabled:            metricPgbouncerDatabaseDisabled{data: pmetric.NewMetric(), config: config.PgbouncerDatabaseDisabled},
		metricPgbouncerDatabasePaused:              metricPgbouncerDatabasePaused{data: pmetric.NewMetric(), config: config.PgbouncerDatabasePaused},
		metricPgbouncerDatabaseReservePoolSize:     metricPgbouncerDatabaseReservePoolSize{data: pmetric.NewMetric(), config: config.PgbouncerDatabaseReservePoolSize},
		metricPgbouncerDNSCacheCount:               metricPgbouncerDNSCacheCount{data: pmetric.NewMetric(), config: config.PgbouncerDNSCacheCount},
		metricPgbouncerDNSQueryCount:               metricPgbouncerDNSQueryCount{data: pmetric.NewMetric(), config: config.PgbouncerDNSQueryCount},
		metricPgbouncerNetworkIO:                   metricPgbouncerNetworkIO{data: pmetric.NewMetric(), config: config.PgbouncerNetworkIO},
		metricPgbouncerPoolCount:                   metricPgbouncerPoolCount{data: pmetric.NewMetric(), config: config.PgbouncerPoolCount},
		metricPgbouncerPreparedStatementCount:      metricPgbouncerPreparedStatementCount{data: pmetric.NewMetric(), config: config.PgbouncerPreparedStatementCount},
		metricPgbouncerQueryCount:                  metricPgbouncerQueryCount{data: pmetric.NewMetric(), config: config.PgbouncerQueryCount},
		metricPgbouncerQueryTime:                   metricPgbouncerQueryTime{data: pmetric.NewMetric(), config: config.PgbouncerQueryTime},
		metricPgbouncerServerAssignmentCount:       metricPgbouncerServerAssignmentCount{data: pmetric.NewMetric(), config: config.PgbouncerServerAssignmentCount},
		metricPgbouncerServerCount:                 metricPgbouncerServerCount{data: pmetric.NewMetric(), config: config.PgbouncerServerCount},
		metricPgbouncerTransactionCount:            metricPgbouncerTransactionCount{data: pmetric.NewMetric(), config: config.PgbouncerTransactionCount},
		metricPgbouncerTransactionTime:             metricPgbouncerTransactionTime{data: pmetric.NewMetric(), config: config.PgbouncerTransactionTime},
		metricPgbouncerUserConnectionMax:           metricPgbouncerUserConnectionMax{data: pmetric.NewMetric(), config: config.PgbouncerUserConnectionMax},
		metricPgbouncerUserCount:                   metricPgbouncerUserCount{data: pmetric.NewMetric(), config: config.PgbouncerUserCount},
	}
	mb.metricDBClientConnectionCount.init()
	mb.metricDBClientConnectionIdleMin.init()
	mb.metricDBClientConnectionMax.init()
	mb.metricDBClientConnectionPendingRequests.init()
	mb.metricPgbouncerClientConnectionCount.init()
	mb.metricPgbouncerClientConnectionDetailCount.init()
	mb.metricPgbouncerClientConnectionMax.init()
	mb.metricPgbouncerClientCount.init()
	mb.metricPgbouncerClientWaitMax.init()
	mb.metricPgbouncerClientWaitTime.init()
	mb.metricPgbouncerDatabaseConnectionCount.init()
	mb.metricPgbouncerDatabaseConnectionMax.init()
	mb.metricPgbouncerDatabaseCount.init()
	mb.metricPgbouncerDatabaseDisabled.init()
	mb.metricPgbouncerDatabasePaused.init()
	mb.metricPgbouncerDatabaseReservePoolSize.init()
	mb.metricPgbouncerDNSCacheCount.init()
	mb.metricPgbouncerDNSQueryCount.init()
	mb.metricPgbouncerNetworkIO.init()
	mb.metricPgbouncerPoolCount.init()
	mb.metricPgbouncerPreparedStatementCount.init()
	mb.metricPgbouncerQueryCount.init()
	mb.metricPgbouncerQueryTime.init()
	mb.metricPgbouncerServerAssignmentCount.init()
	mb.metricPgbouncerServerCount.init()
	mb.metricPgbouncerTransactionCount.init()
	mb.metricPgbouncerTransactionTime.init()
	mb.metricPgbouncerUserConnectionMax.init()
	mb.metricPgbouncerUserCount.init()
	return mb
}

// RecordDBClientConnectionCount records one datapoint of db.client.connection.count.
//
// Connections PgBouncer holds to PostgreSQL, by state.
//
// One datapoint per (pool, state). PgBouncer reports seven server states and `db.client.connection.state` defines two, so five carry local values: `used_pending_check`, `tested`, `login`, `active_cancel`, `being_canceled`.
// `sv_used` is deliberately *not* reported as `used`. PgBouncer's `sv_used` means idle for longer than `server_check_delay` and needing a check query before reuse -- an idle connection. Upstream `used` means in use, which is `sv_active`. Aliasing the two by name would double-count against `sv_active` and invert the metric people alert on.
//
// Instrument: updowncounter. Unit: {connection}. Stability: development.
func (mb *MetricsBuilder) RecordDBClientConnectionCount(ts pcommon.Timestamp, value int64, attrs DBClientConnectionCountAttributes) {
	mb.metricDBClientConnectionCount.record(mb.startTime, ts, value, attrs)
}

// RecordDBClientConnectionIdleMin records one datapoint of db.client.connection.idle.min.
//
// Server connections PgBouncer keeps open when idle.
//
// PgBouncer's `min_pool_size`, from `SHOW DATABASES`. The upstream exporter does not emit it; it is surface we add, so it has no Prometheus source and is excluded from the compat scope.
//
// Instrument: updowncounter. Unit: {connection}. Stability: development.
func (mb *MetricsBuilder) RecordDBClientConnectionIdleMin(ts pcommon.Timestamp, value int64, attrs DBClientConnectionIdleMinAttributes) {
	mb.metricDBClientConnectionIdleMin.record(mb.startTime, ts, value, attrs)
}

// RecordDBClientConnectionMax records one datapoint of db.client.connection.max.
//
// Maximum server connections PgBouncer will open for a pool.
//
// PgBouncer's `pool_size`, from `SHOW DATABASES`.
//
// Instrument: updowncounter. Unit: {connection}. Stability: development.
func (mb *MetricsBuilder) RecordDBClientConnectionMax(ts pcommon.Timestamp, value int64, attrs DBClientConnectionMaxAttributes) {
	mb.metricDBClientConnectionMax.record(mb.startTime, ts, value, attrs)
}

// RecordDBClientConnectionPendingRequests records one datapoint of db.client.connection.pending_requests.
//
// Clients queued waiting for a server connection.
//
// PgBouncer's `cl_waiting`, from `SHOW POOLS`. Reported here because it is exactly the convention's "current pending requests for an open connection" against the server pool, and again as `pgbouncer.client.connection.count{state=waiting}` because it is also a client-side state. The same number under two names is deliberate: the first is the semconv-native view of pool saturation, the second completes the client-side state breakdown.
//
// Instrument: updowncounter. Unit: {request}. Stability: development.
func (mb *MetricsBuilder) RecordDBClientConnectionPendingRequests(ts pcommon.Timestamp, value int64, attrs DBClientConnectionPendingRequestsAttributes) {
	mb.metricDBClientConnectionPendingRequests.record(mb.startTime, ts, value, attrs)
}

// RecordPgbouncerClientConnectionCount records one datapoint of pgbouncer.client.connection.count.
//
// Client connections held by PgBouncer, by state.
//
// The application-facing half of the pooler, which upstream `db.client.connection.*` does not model -- that convention describes a pool a client holds *to* a database, which here is the PostgreSQL side. Candidate semconv contribution once a second proxy provides evidence.
//
// Instrument: updowncounter. Unit: {connection}. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerClientConnectionCount(ts pcommon.Timestamp, value int64, attrs PgbouncerClientConnectionCountAttributes) {
	mb.metricPgbouncerClientConnectionCount.record(mb.startTime, ts, value, attrs)
}

// RecordPgbouncerClientConnectionDetailCount records one datapoint of pgbouncer.client.connection.detail.count.
//
// Client connections aggregated by database, role and connection state.
//
// From `SHOW CLIENTS`, at a finer grain than `SHOW POOLS`.
// The upstream exporter also dimensions this by `application_name`, which is set by the connecting client and is therefore unbounded by construction -- it is the label that turns a three-series metric into an N-series one. It is dropped here and the count aggregated over the remaining keys.
// The compat scope keeps `application_name`, because a user cutting over must see their existing series unchanged. That series cannot be reconstructed from this metric, which is why this entry is the one `compat_source: native` in the component.
//
// Instrument: updowncounter. Unit: {connection}. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerClientConnectionDetailCount(ts pcommon.Timestamp, value int64, attrs PgbouncerClientConnectionDetailCountAttributes) {
	mb.metricPgbouncerClientConnectionDetailCount.record(mb.startTime, ts, value, attrs)
}

// RecordPgbouncerClientConnectionMax records one datapoint of pgbouncer.client.connection.max.
//
// Maximum client connections PgBouncer accepts process-wide.
//
// PgBouncer's `max_client_conn`, from `SHOW CONFIG`. Distinct from `db.client.connection.max`, which is the per-pool `pool_size` on the PostgreSQL side.
//
// Instrument: updowncounter. Unit: {connection}. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerClientConnectionMax(ts pcommon.Timestamp, value int64) {
	mb.metricPgbouncerClientConnectionMax.record(mb.startTime, ts, value)
}

// RecordPgbouncerClientCount records one datapoint of pgbouncer.client.count.
//
// Client slots, by state.
//
// Instrument: updowncounter. Unit: {client}. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerClientCount(ts pcommon.Timestamp, value int64, attrs PgbouncerClientCountAttributes) {
	mb.metricPgbouncerClientCount.record(mb.startTime, ts, value, attrs)
}

// RecordPgbouncerClientWaitMax records one datapoint of pgbouncer.client.wait.max.
//
// Age of the oldest client connection still waiting for a server connection.
//
// PgBouncer's `maxwait`/`maxwait_us`, from `SHOW POOLS`. A non-zero value is the direct signal that a pool is saturated.
//
// Instrument: gauge. Unit: s. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerClientWaitMax(ts pcommon.Timestamp, value float64, attrs PgbouncerClientWaitMaxAttributes) {
	mb.metricPgbouncerClientWaitMax.record(mb.startTime, ts, value, attrs)
}

// RecordPgbouncerClientWaitTime records one datapoint of pgbouncer.client.wait.time.
//
// Time clients have spent waiting for a server connection.
//
// Upstream `db.client.connection.wait_time` is semantically exact but is a **histogram**, and PgBouncer exposes only `total_wait_time`, a cumulative counter. A histogram with invented bounds passes review because the name looks right, so this is reported as a sum under a local name instead.
//
// Instrument: counter. Unit: s. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerClientWaitTime(ts pcommon.Timestamp, value float64, attrs PgbouncerClientWaitTimeAttributes) {
	mb.metricPgbouncerClientWaitTime.record(mb.startTime, ts, value, attrs)
}

// RecordPgbouncerDatabaseConnectionCount records one datapoint of pgbouncer.database.connection.count.
//
// Server connections currently open for a configured database.
//
// Instrument: updowncounter. Unit: {connection}. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerDatabaseConnectionCount(ts pcommon.Timestamp, value int64, attrs PgbouncerDatabaseConnectionCountAttributes) {
	mb.metricPgbouncerDatabaseConnectionCount.record(mb.startTime, ts, value, attrs)
}

// RecordPgbouncerDatabaseConnectionMax records one datapoint of pgbouncer.database.connection.max.
//
// Maximum server connections allowed for a configured database.
//
// PgBouncer's `max_db_connections`, a ceiling across all pools for the database. Distinct from `db.client.connection.max`, which is one pool's `pool_size`.
//
// Instrument: updowncounter. Unit: {connection}. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerDatabaseConnectionMax(ts pcommon.Timestamp, value int64, attrs PgbouncerDatabaseConnectionMaxAttributes) {
	mb.metricPgbouncerDatabaseConnectionMax.record(mb.startTime, ts, value, attrs)
}

// RecordPgbouncerDatabaseCount records one datapoint of pgbouncer.database.count.
//
// Databases configured in PgBouncer.
//
// Instrument: updowncounter. Unit: {database}. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerDatabaseCount(ts pcommon.Timestamp, value int64) {
	mb.metricPgbouncerDatabaseCount.record(mb.startTime, ts, value)
}

// RecordPgbouncerDatabaseDisabled records one datapoint of pgbouncer.database.disabled.
//
// 1 while a configured database is disabled, else 0.
//
// Instrument: gauge. Unit: 1. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerDatabaseDisabled(ts pcommon.Timestamp, value int64, attrs PgbouncerDatabaseDisabledAttributes) {
	mb.metricPgbouncerDatabaseDisabled.record(mb.startTime, ts, value, attrs)
}

// RecordPgbouncerDatabasePaused records one datapoint of pgbouncer.database.paused.
//
// 1 while a configured database is paused, else 0.
//
// Instrument: gauge. Unit: 1. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerDatabasePaused(ts pcommon.Timestamp, value int64, attrs PgbouncerDatabasePausedAttributes) {
	mb.metricPgbouncerDatabasePaused.record(mb.startTime, ts, value, attrs)
}

// RecordPgbouncerDatabaseReservePoolSize records one datapoint of pgbouncer.database.reserve_pool.size.
//
// Additional server connections allowed once a pool is saturated.
//
// Instrument: updowncounter. Unit: {connection}. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerDatabaseReservePoolSize(ts pcommon.Timestamp, value int64, attrs PgbouncerDatabaseReservePoolSizeAttributes) {
	mb.metricPgbouncerDatabaseReservePoolSize.record(mb.startTime, ts, value, attrs)
}

// RecordPgbouncerDNSCacheCount records one datapoint of pgbouncer.dns.cache.count.
//
// Entries in PgBouncer's DNS cache.
//
// Instrument: updowncounter. Unit: {entry}. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerDNSCacheCount(ts pcommon.Timestamp, value int64, attrs PgbouncerDNSCacheCountAttributes) {
	mb.metricPgbouncerDNSCacheCount.record(mb.startTime, ts, value, attrs)
}

// RecordPgbouncerDNSQueryCount records one datapoint of pgbouncer.dns.query.count.
//
// DNS queries PgBouncer has in flight.
//
// Instrument: updowncounter. Unit: {query}. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerDNSQueryCount(ts pcommon.Timestamp, value int64) {
	mb.metricPgbouncerDNSQueryCount.record(mb.startTime, ts, value)
}

// RecordPgbouncerNetworkIO records one datapoint of pgbouncer.network.io.
//
// Network traffic PgBouncer has proxied.
//
// `network.io.direction` is `release_candidate`, not stable -- recorded in the component stability block.
//
// Instrument: counter. Unit: By. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerNetworkIO(ts pcommon.Timestamp, value int64, attrs PgbouncerNetworkIOAttributes) {
	mb.metricPgbouncerNetworkIO.record(mb.startTime, ts, value, attrs)
}

// RecordPgbouncerPoolCount records one datapoint of pgbouncer.pool.count.
//
// Active connection pools.
//
// Instrument: updowncounter. Unit: {pool}. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerPoolCount(ts pcommon.Timestamp, value int64) {
	mb.metricPgbouncerPoolCount.record(mb.startTime, ts, value)
}

// RecordPgbouncerPreparedStatementCount records one datapoint of pgbouncer.prepared_statement.count.
//
// Extended-query-protocol messages PgBouncer handled for prepared statements.
//
// `pgbouncer.peer` separates the Parse messages PgBouncer received from clients from those it forwarded to PostgreSQL; the gap between them is what prepared-statement pooling saves. Bind messages are counted once and carry no peer.
//
// Instrument: counter. Unit: {message}. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerPreparedStatementCount(ts pcommon.Timestamp, value int64, attrs PgbouncerPreparedStatementCountAttributes) {
	mb.metricPgbouncerPreparedStatementCount.record(mb.startTime, ts, value, attrs)
}

// RecordPgbouncerQueryCount records one datapoint of pgbouncer.query.count.
//
// SQL queries pooled by PgBouncer.
//
// Instrument: counter. Unit: {query}. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerQueryCount(ts pcommon.Timestamp, value int64, attrs PgbouncerQueryCountAttributes) {
	mb.metricPgbouncerQueryCount.record(mb.startTime, ts, value, attrs)
}

// RecordPgbouncerQueryTime records one datapoint of pgbouncer.query.time.
//
// Time PgBouncer spent executing queries against PostgreSQL.
//
// Upstream `db.client.operation.duration` is stable and is exactly this measurement, but it is a **histogram** and PgBouncer exposes only `total_query_time`, a cumulative counter. Reporting a single-bucket histogram under the released name would be a lie that passes review because the name looks right.
//
// Instrument: counter. Unit: s. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerQueryTime(ts pcommon.Timestamp, value float64, attrs PgbouncerQueryTimeAttributes) {
	mb.metricPgbouncerQueryTime.record(mb.startTime, ts, value, attrs)
}

// RecordPgbouncerServerAssignmentCount records one datapoint of pgbouncer.server.assignment.count.
//
// Client connections assigned a server connection since process start.
//
// Instrument: counter. Unit: {assignment}. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerServerAssignmentCount(ts pcommon.Timestamp, value int64, attrs PgbouncerServerAssignmentCountAttributes) {
	mb.metricPgbouncerServerAssignmentCount.record(mb.startTime, ts, value, attrs)
}

// RecordPgbouncerServerCount records one datapoint of pgbouncer.server.count.
//
// Server slots, by state.
//
// Instrument: updowncounter. Unit: {server}. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerServerCount(ts pcommon.Timestamp, value int64, attrs PgbouncerServerCountAttributes) {
	mb.metricPgbouncerServerCount.record(mb.startTime, ts, value, attrs)
}

// RecordPgbouncerTransactionCount records one datapoint of pgbouncer.transaction.count.
//
// SQL transactions pooled by PgBouncer.
//
// Instrument: counter. Unit: {transaction}. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerTransactionCount(ts pcommon.Timestamp, value int64, attrs PgbouncerTransactionCountAttributes) {
	mb.metricPgbouncerTransactionCount.record(mb.startTime, ts, value, attrs)
}

// RecordPgbouncerTransactionTime records one datapoint of pgbouncer.transaction.time.
//
// Time PgBouncer server connections spent inside a transaction.
//
// Includes time idle in transaction, so it exceeds `pgbouncer.query.time`. The gap between the two is the classic idle-in-transaction signal.
//
// Instrument: counter. Unit: s. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerTransactionTime(ts pcommon.Timestamp, value float64, attrs PgbouncerTransactionTimeAttributes) {
	mb.metricPgbouncerTransactionTime.record(mb.startTime, ts, value, attrs)
}

// RecordPgbouncerUserConnectionMax records one datapoint of pgbouncer.user.connection.max.
//
// Maximum server connections PgBouncer opens per login role.
//
// PgBouncer's `max_user_connections`, from `SHOW CONFIG`.
//
// Instrument: updowncounter. Unit: {connection}. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerUserConnectionMax(ts pcommon.Timestamp, value int64) {
	mb.metricPgbouncerUserConnectionMax.record(mb.startTime, ts, value)
}

// RecordPgbouncerUserCount records one datapoint of pgbouncer.user.count.
//
// Login roles known to PgBouncer.
//
// Instrument: updowncounter. Unit: {user}. Stability: development.
func (mb *MetricsBuilder) RecordPgbouncerUserCount(ts pcommon.Timestamp, value int64) {
	mb.metricPgbouncerUserCount.record(mb.startTime, ts, value)
}

// Emit moves everything recorded since the last call into a pmetric.Metrics
// under resource, leaving the builder empty and ready for the next scrape.
func (mb *MetricsBuilder) Emit(resource pcommon.Resource) pmetric.Metrics {
	md := pmetric.NewMetrics()
	rm := md.ResourceMetrics().AppendEmpty()
	resource.CopyTo(rm.Resource())

	sm := rm.ScopeMetrics().AppendEmpty()
	sm.Scope().SetName(mb.scopeName)
	sm.Scope().SetVersion(mb.scopeVersion)
	ms := sm.Metrics()
	mb.metricDBClientConnectionCount.emit(ms)
	mb.metricDBClientConnectionIdleMin.emit(ms)
	mb.metricDBClientConnectionMax.emit(ms)
	mb.metricDBClientConnectionPendingRequests.emit(ms)
	mb.metricPgbouncerClientConnectionCount.emit(ms)
	mb.metricPgbouncerClientConnectionDetailCount.emit(ms)
	mb.metricPgbouncerClientConnectionMax.emit(ms)
	mb.metricPgbouncerClientCount.emit(ms)
	mb.metricPgbouncerClientWaitMax.emit(ms)
	mb.metricPgbouncerClientWaitTime.emit(ms)
	mb.metricPgbouncerDatabaseConnectionCount.emit(ms)
	mb.metricPgbouncerDatabaseConnectionMax.emit(ms)
	mb.metricPgbouncerDatabaseCount.emit(ms)
	mb.metricPgbouncerDatabaseDisabled.emit(ms)
	mb.metricPgbouncerDatabasePaused.emit(ms)
	mb.metricPgbouncerDatabaseReservePoolSize.emit(ms)
	mb.metricPgbouncerDNSCacheCount.emit(ms)
	mb.metricPgbouncerDNSQueryCount.emit(ms)
	mb.metricPgbouncerNetworkIO.emit(ms)
	mb.metricPgbouncerPoolCount.emit(ms)
	mb.metricPgbouncerPreparedStatementCount.emit(ms)
	mb.metricPgbouncerQueryCount.emit(ms)
	mb.metricPgbouncerQueryTime.emit(ms)
	mb.metricPgbouncerServerAssignmentCount.emit(ms)
	mb.metricPgbouncerServerCount.emit(ms)
	mb.metricPgbouncerTransactionCount.emit(ms)
	mb.metricPgbouncerTransactionTime.emit(ms)
	mb.metricPgbouncerUserConnectionMax.emit(ms)
	mb.metricPgbouncerUserCount.emit(ms)

	// A scrape that recorded nothing produces no scope and no resource, rather
	// than an empty envelope downstream has to filter out.
	if ms.Len() == 0 {
		return pmetric.NewMetrics()
	}
	return md
}
