// Code generated by weaver. DO NOT EDIT.
// Source: https://olly.garden/schemas/grafts/pgbouncerreceiver/0.1.0

package telemetry

import "go.olly.garden/grafts/internal/promcompat"

// CompatTable is every OTel metric with a Prometheus counterpart. Entries the
// registry marks `emit_prometheus: false` carry no Series: they are surface the
// upstream exporter does not have, or the losing half of a `split` whose compat
// series another entry already owns.
var CompatTable = []promcompat.Entry{
	{
		Metric:      "db.client.connection.count",
		Type:        "gauge",
		Source:      promcompat.SourceDerived,
		Disposition: "merge",
		Labels: map[string]string{
			"pgbouncer.database.alias": "database",
			"pgbouncer.user":           "user",
		},
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_pools_server_active_connections",
				When: map[string]string{
					"db.client.connection.state": "used",
				},
			},
			{
				Name: "pgbouncer_pools_server_idle_connections",
				When: map[string]string{
					"db.client.connection.state": "idle",
				},
			},
			{
				Name: "pgbouncer_pools_server_used_connections",
				When: map[string]string{
					"db.client.connection.state": "used_pending_check",
				},
			},
			{
				Name: "pgbouncer_pools_server_testing_connections",
				When: map[string]string{
					"db.client.connection.state": "tested",
				},
			},
			{
				Name: "pgbouncer_pools_server_login_connections",
				When: map[string]string{
					"db.client.connection.state": "login",
				},
			},
			{
				Name: "pgbouncer_pools_server_active_cancel_connections",
				When: map[string]string{
					"db.client.connection.state": "active_cancel",
				},
			},
			{
				Name: "pgbouncer_pools_server_being_canceled_connections",
				When: map[string]string{
					"db.client.connection.state": "being_canceled",
				},
			},
		},
	},
	{
		Metric:      "db.client.connection.idle.min",
		Type:        "gauge",
		Source:      promcompat.SourceDerived,
		Disposition: "extra",
	},
	{
		Metric:      "db.client.connection.max",
		Type:        "gauge",
		Source:      promcompat.SourceNative,
		Disposition: "map",
		Labels: map[string]string{
			"db.namespace":             "database",
			"pgbouncer.database.alias": "name",
			"server.address":           "host",
			"server.port":              "port",
		},
		Dropped: []string{
			"force_user",
			"pool_mode",
		},
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_databases_pool_size",
			},
		},
	},
	{
		Metric:      "db.client.connection.pending_requests",
		Type:        "gauge",
		Source:      promcompat.SourceDerived,
		Disposition: "split",
	},
	{
		Metric:      "pgbouncer.client.connection.count",
		Type:        "gauge",
		Source:      promcompat.SourceDerived,
		Disposition: "merge",
		Labels: map[string]string{
			"pgbouncer.database.alias": "database",
			"pgbouncer.user":           "user",
		},
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_pools_client_active_connections",
				When: map[string]string{
					"pgbouncer.client.connection.state": "active",
				},
			},
			{
				Name: "pgbouncer_pools_client_waiting_connections",
				When: map[string]string{
					"pgbouncer.client.connection.state": "waiting",
				},
			},
			{
				Name: "pgbouncer_pools_client_active_cancel_connections",
				When: map[string]string{
					"pgbouncer.client.connection.state": "active_cancel",
				},
			},
			{
				Name: "pgbouncer_pools_client_waiting_cancel_connections",
				When: map[string]string{
					"pgbouncer.client.connection.state": "waiting_cancel",
				},
			},
		},
	},
	{
		Metric:      "pgbouncer.client.connection.detail.count",
		Type:        "gauge",
		Source:      promcompat.SourceNative,
		Disposition: "map",
		Labels: map[string]string{
			"pgbouncer.client.state":   "state",
			"pgbouncer.database.alias": "database",
			"pgbouncer.user":           "user",
		},
		Dropped: []string{
			"application_name",
		},
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_client_connections",
			},
		},
	},
	{
		Metric:      "pgbouncer.client.connection.max",
		Type:        "gauge",
		Source:      promcompat.SourceDerived,
		Disposition: "rename",
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_config_max_client_connections",
			},
		},
	},
	{
		Metric:      "pgbouncer.client.count",
		Type:        "gauge",
		Source:      promcompat.SourceDerived,
		Disposition: "merge",
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_free_clients",
				When: map[string]string{
					"pgbouncer.client.state": "free",
				},
			},
			{
				Name: "pgbouncer_used_clients",
				When: map[string]string{
					"pgbouncer.client.state": "used",
				},
			},
			{
				Name: "pgbouncer_login_clients",
				When: map[string]string{
					"pgbouncer.client.state": "login",
				},
			},
		},
	},
	{
		Metric:      "pgbouncer.client.wait.max",
		Type:        "gauge",
		Source:      promcompat.SourceDerived,
		Disposition: "rename",
		Labels: map[string]string{
			"pgbouncer.database.alias": "database",
			"pgbouncer.user":           "user",
		},
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_pools_client_maxwait_seconds",
			},
		},
	},
	{
		Metric:      "pgbouncer.client.wait.time",
		Type:        "counter",
		Source:      promcompat.SourceDerived,
		Disposition: "rename",
		Labels: map[string]string{
			"pgbouncer.database.alias": "database",
		},
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_stats_totals_client_wait_seconds_total",
			},
		},
	},
	{
		Metric:      "pgbouncer.database.connection.count",
		Type:        "gauge",
		Source:      promcompat.SourceNative,
		Disposition: "rename",
		Labels: map[string]string{
			"db.namespace":             "database",
			"pgbouncer.database.alias": "name",
			"server.address":           "host",
			"server.port":              "port",
		},
		Dropped: []string{
			"force_user",
			"pool_mode",
		},
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_databases_current_connections",
			},
		},
	},
	{
		Metric:      "pgbouncer.database.connection.max",
		Type:        "gauge",
		Source:      promcompat.SourceNative,
		Disposition: "rename",
		Labels: map[string]string{
			"db.namespace":             "database",
			"pgbouncer.database.alias": "name",
			"server.address":           "host",
			"server.port":              "port",
		},
		Dropped: []string{
			"force_user",
			"pool_mode",
		},
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_databases_max_connections",
			},
		},
	},
	{
		Metric:      "pgbouncer.database.count",
		Type:        "gauge",
		Source:      promcompat.SourceDerived,
		Disposition: "rename",
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_databases",
			},
		},
	},
	{
		Metric:      "pgbouncer.database.disabled",
		Type:        "gauge",
		Source:      promcompat.SourceNative,
		Disposition: "map",
		Labels: map[string]string{
			"db.namespace":             "database",
			"pgbouncer.database.alias": "name",
			"server.address":           "host",
			"server.port":              "port",
		},
		Dropped: []string{
			"force_user",
			"pool_mode",
		},
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_databases_disabled",
			},
		},
	},
	{
		Metric:      "pgbouncer.database.paused",
		Type:        "gauge",
		Source:      promcompat.SourceNative,
		Disposition: "map",
		Labels: map[string]string{
			"db.namespace":             "database",
			"pgbouncer.database.alias": "name",
			"server.address":           "host",
			"server.port":              "port",
		},
		Dropped: []string{
			"force_user",
			"pool_mode",
		},
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_databases_paused",
			},
		},
	},
	{
		Metric:      "pgbouncer.database.reserve_pool.size",
		Type:        "gauge",
		Source:      promcompat.SourceNative,
		Disposition: "rename",
		Labels: map[string]string{
			"db.namespace":             "database",
			"pgbouncer.database.alias": "name",
			"server.address":           "host",
			"server.port":              "port",
		},
		Dropped: []string{
			"force_user",
			"pool_mode",
		},
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_databases_reserve_pool",
			},
		},
	},
	{
		Metric:      "pgbouncer.dns.cache.count",
		Type:        "gauge",
		Source:      promcompat.SourceDerived,
		Disposition: "merge",
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_cached_dns_names",
				When: map[string]string{
					"pgbouncer.dns.cache.type": "name",
				},
			},
			{
				Name: "pgbouncer_cached_dns_zones",
				When: map[string]string{
					"pgbouncer.dns.cache.type": "zone",
				},
			},
		},
	},
	{
		Metric:      "pgbouncer.dns.query.count",
		Type:        "gauge",
		Source:      promcompat.SourceDerived,
		Disposition: "rename",
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_in_flight_dns_queries",
			},
		},
	},
	{
		Metric:      "pgbouncer.network.io",
		Type:        "counter",
		Source:      promcompat.SourceDerived,
		Disposition: "merge",
		Labels: map[string]string{
			"pgbouncer.database.alias": "database",
		},
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_stats_totals_received_bytes_total",
				When: map[string]string{
					"network.io.direction": "receive",
				},
			},
			{
				Name: "pgbouncer_stats_totals_sent_bytes_total",
				When: map[string]string{
					"network.io.direction": "transmit",
				},
			},
		},
	},
	{
		Metric:      "pgbouncer.pool.count",
		Type:        "gauge",
		Source:      promcompat.SourceDerived,
		Disposition: "rename",
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_pools",
			},
		},
	},
	{
		Metric:      "pgbouncer.prepared_statement.count",
		Type:        "counter",
		Source:      promcompat.SourceDerived,
		Disposition: "merge",
		Labels: map[string]string{
			"pgbouncer.database.alias": "database",
		},
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_stats_totals_client_parses_total",
				When: map[string]string{
					"pgbouncer.peer":                         "client",
					"pgbouncer.prepared_statement.operation": "parse",
				},
			},
			{
				Name: "pgbouncer_stats_totals_server_parses_total",
				When: map[string]string{
					"pgbouncer.peer":                         "server",
					"pgbouncer.prepared_statement.operation": "parse",
				},
			},
			{
				Name: "pgbouncer_stats_totals_binds_total",
				When: map[string]string{
					"pgbouncer.prepared_statement.operation": "bind",
				},
			},
		},
	},
	{
		Metric:      "pgbouncer.query.count",
		Type:        "counter",
		Source:      promcompat.SourceDerived,
		Disposition: "rename",
		Labels: map[string]string{
			"pgbouncer.database.alias": "database",
		},
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_stats_totals_queries_pooled_total",
			},
		},
	},
	{
		Metric:      "pgbouncer.query.time",
		Type:        "counter",
		Source:      promcompat.SourceDerived,
		Disposition: "rename",
		Labels: map[string]string{
			"pgbouncer.database.alias": "database",
		},
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_stats_totals_queries_duration_seconds_total",
			},
		},
	},
	{
		Metric:      "pgbouncer.server.assignment.count",
		Type:        "counter",
		Source:      promcompat.SourceDerived,
		Disposition: "rename",
		Labels: map[string]string{
			"pgbouncer.database.alias": "database",
		},
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_stats_totals_server_assignments_total",
			},
		},
	},
	{
		Metric:      "pgbouncer.server.count",
		Type:        "gauge",
		Source:      promcompat.SourceDerived,
		Disposition: "merge",
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_free_servers",
				When: map[string]string{
					"pgbouncer.server.state": "free",
				},
			},
			{
				Name: "pgbouncer_used_servers",
				When: map[string]string{
					"pgbouncer.server.state": "used",
				},
			},
		},
	},
	{
		Metric:      "pgbouncer.transaction.count",
		Type:        "counter",
		Source:      promcompat.SourceDerived,
		Disposition: "rename",
		Labels: map[string]string{
			"pgbouncer.database.alias": "database",
		},
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_stats_totals_sql_transactions_pooled_total",
			},
		},
	},
	{
		Metric:      "pgbouncer.transaction.time",
		Type:        "counter",
		Source:      promcompat.SourceDerived,
		Disposition: "rename",
		Labels: map[string]string{
			"pgbouncer.database.alias": "database",
		},
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_stats_totals_server_in_transaction_seconds_total",
			},
		},
	},
	{
		Metric:      "pgbouncer.user.connection.max",
		Type:        "gauge",
		Source:      promcompat.SourceDerived,
		Disposition: "rename",
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_config_max_user_connections",
			},
		},
	},
	{
		Metric:      "pgbouncer.user.count",
		Type:        "gauge",
		Source:      promcompat.SourceDerived,
		Disposition: "rename",
		Series: []promcompat.Series{
			{
				Name: "pgbouncer_users",
			},
		},
	},
}
