// Code generated by weaver. DO NOT EDIT.
// Source: https://olly.garden/schemas/grafts/pgbouncerreceiver/0.1.0

package telemetry

import (
	"context"
	"fmt"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
)

// SelfTelemetry holds the instruments pgbouncerreceiver reports about its own
// operation, as distinct from the metrics it reports about the system it
// monitors.
//
// Declaring both in one registry is what makes `weaver registry check` a
// complete gate: a component cannot quietly grow an undeclared instrument on
// either side.
type SelfTelemetry struct {
	// ScrapeDuration reports pgbouncerreceiver.scrape.duration: Time taken by a full scrape of the PgBouncer admin console.
	ScrapeDuration metric.Float64Histogram
	// ScrapeErrors reports pgbouncerreceiver.scrape.errors: Scrape steps that failed.
	ScrapeErrors metric.Int64Counter
}

// NewSelfTelemetry creates the component's instruments on the provider the
// Collector supplies. An instrument that cannot be created is returned as an
// error rather than left nil, so a mistake surfaces at startup instead of as a
// panic on the first scrape.
func NewSelfTelemetry(provider metric.MeterProvider, scopeName string) (*SelfTelemetry, error) {
	meter := provider.Meter(scopeName)
	t := &SelfTelemetry{}

	var err error
	if t.ScrapeDuration, err = meter.Float64Histogram(
		"pgbouncerreceiver.scrape.duration",
		metric.WithDescription("Time taken by a full scrape of the PgBouncer admin console."),
		metric.WithUnit("s"),
	); err != nil {
		return nil, fmt.Errorf("creating pgbouncerreceiver.scrape.duration: %w", err)
	}
	if t.ScrapeErrors, err = meter.Int64Counter(
		"pgbouncerreceiver.scrape.errors",
		metric.WithDescription("Scrape steps that failed."),
		metric.WithUnit("{error}"),
	); err != nil {
		return nil, fmt.Errorf("creating pgbouncerreceiver.scrape.errors: %w", err)
	}

	return t, nil
}

// RecordScrapeDuration records pgbouncerreceiver.scrape.duration.
//
// Time taken by a full scrape of the PgBouncer admin console.
//
// One observation per collection interval, covering every command. Per command timing is not reported: it would multiply the series set by the command count for a number only useful while debugging.
func (t *SelfTelemetry) RecordScrapeDuration(ctx context.Context, value float64) {
	t.ScrapeDuration.Record(ctx, value)
}

// RecordScrapeErrors records pgbouncerreceiver.scrape.errors.
//
// Scrape steps that failed.
//
// A scrape is partial rather than all-or-nothing -- the receiver reports what it got and records the failures here, matching the behaviour users depend on from the upstream exporter. `error.type` classifies the failure; it never carries a message read off the connection.
func (t *SelfTelemetry) RecordScrapeErrors(ctx context.Context, value int64, errorType string, pgbouncerreceiverCommand string) {
	t.ScrapeErrors.Add(ctx, value, metric.WithAttributes(
		attribute.String("error.type", errorType),
		attribute.String("pgbouncerreceiver.command", pgbouncerreceiverCommand),
	))
}
