name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: blacksmith
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: 1.24

      - name: Setup access for private go modules
        run: |
          git config --global url."https://git:$GO_GITHUB_TOKEN@github.com".insteadOf "https://github.com"
        env:
          GO_GITHUB_TOKEN: ${{ secrets.GO_GITHUB_TOKEN }}

      - name: Check go mod tidy
        run: make tidy && git diff --exit-code

      - name: Build
        run: make build

      - name: Lint
        run: make lint

      - name: Test
        run: make test
